[package]
name = "aquarium-lib"
version = "0.1.0"
authors = ["Amit Prasad <mail@amitprasad.dev>"]
edition = "2021"

[dependencies]
anyhow = "1"
async-trait = "0.1.65"
base64 = "0.21.0"
clap = { version = "4.1.8", features = ["derive"] }
cosmrs = { git = "https://github.com/cosmos/cosmos-rust", features = ["cosmwasm"] }
reqwest = { version = "0.11.14", features = ["json"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1.0.93"
tokio = { version = "1.26.0", features = ["full"] }
