[package]
name = "aquarium-macro"
version = "0.1.0"
authors = ["Amit Prasad <mail@amitprasad.dev>"]
edition = "2021"
description = "Macros for Aquarium"
repository = "https://github.com/AmitPr/aquarium"
license = "MIT"

[lib]
proc-macro = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quote = "1.0.23"
syn = { version = "1.0.109", features = ["full"] }
